kind: Service
apiVersion: v1
metadata:
  name: hellojenkins
spec:
  type: NodePort
  selector:
    app: hellojenkins
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellojenkins
  labels:
    app: hellojenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellojenkins
  template:
    metadata:
      labels:
        app: hellojenkins
    spec:
      containers:
      - name: app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
